version: '3.1'

services:
  # poc-cruzeiro-node-ts:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3000:3000'
  #   container_name: poc-cruzeiro-node-ts
  #   restart: always
  #   volumes:
  #     - api_logs:/usr/src/node-api/logs:rw
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - mysql

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - '3306'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: cruzeiro
      MYSQL_DATABASE: cruzeirodb
      MYSQL_USER: cruzeiro
      MYSQL_PASSWORD: cruzeiro

volumes:
  db_data: {}
  api_logs: {}
