version: '3.1'

services:
  poc-cruzeiro-node-ts:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    container_name: poc-cruzeiro-node-ts
    restart: always
    volumes:
      - api_logs:/usr/src/node-api/logs:rw
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    container_name: postgresdb
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'

volumes:
  pg_data: {}
  api_logs: {}
